config/routes.rb
Rails.application.routes.draw do
	get 'sessions/new'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
  #get  'users/new'
  scope module: :default_scope do
  	get  '/signup',      to:'users#new'
  	root 'static_pages#home'
  	get  '/help',        to: 'static_pages#help'
  	get  '/about',       to: 'static_pages#about'
  	get  '/contact',     to: 'static_pages#contact'
    get  '/cloud',       to: 'static_pages#cloud'
  	resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	#before_save { self.email = email.downcase }
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
			          format: { with: VALID_EMAIL_REGEX },
			          uniqueness: true,
			          uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

    # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/default_scope/users_controller.rb
module DefaultScope 
	class UsersController < ApplicationController
		def show
			@user = User.find(params[:id])
      render "default_scope/users/show"
    end

    def new
     @user = User.new
   end

   def create
     @user = User.new(user_params)
     if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  private
  def user_params
   params.require(:user).permit(:name, :email, :password,
    :password_confirmation)
 end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_url(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url  
  end
end

app/controllers/static_pages_controller.rb
module DefaultScope
	class StaticPagesController < ApplicationController
		def home
		end

		def help
		end

		def about
		end

		def contact
		end

		def cloud
		end
		
	end
end

app/controllers/users_controller.rb
module DefaultScope 
	class UsersController < ApplicationController
		def show
			@user = User.find(params[:id])
            render "default_scope/users/show"
		end

		def new
			@user = User.new
		end

		def create
    	@user = User.new(user_params)
    	if @user.save
        flash[:success] = "Welcome to the Sample App!"
      	  redirect_to user_url(@user)
    	else
      		render 'new'
    	end
  	end

    def edit
      @user = User.find(params[:id])
        render "default_scope/users/edit"
    end

  	private
	    def user_params
	      params.require(:user).permit(:name, :email, :password,
	                                   :password_confirmation)
	    end
	end
end

app/helpers/application_helper.rb
require 'url_shortener'
require 'uri'
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    return base_title if page_title.empty?
    return page_title + " | " + base_title
  end

  def tmp_method(content)
    return "" unless content.present?

    authorize = UrlShortener::Authorize.new 'ntokarsk3', 'R_1f8855bd5d204896b7b854adf471b586'
    client = UrlShortener::Client.new(authorize)

    zmienna = client.shorten('http://www.swmansion.com/')

    "zmienna:  #{zmienna}"
  end

  def extractUrls(text)
    URI.extract(text)
  end

  def replaceUrlsWithTrackable(text)

  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    #dopiero image_tag wyswietla orbazek
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/default_scope/static_pages/cloud.html.erb
<script>
var word_list = <%= [
{text: "Lorem", weight: 13},
{text: "Ipsum", weight: 10.5},
{text: "Dolor", weight: 9.4},
{text: "Sit", weight: 8},
{text: "Amet", weight: 6.2},
{text: "Consectetur", weight: 5},
{text: "Adipiscing", weight: 5},
{text: "Elit", weight: 5},
{text: "Nam et", weight: 5},
{text: "Leo", weight: 4},
{text: "Sapien", weight: 4},
{text: "Pellentesque", weight: 3},
{text: "habitant", weight: 3},
{text: "morbi", weight: 3},
{text: "tristisque", weight: 3},
{text: "senectus", weight: 3},
{text: "et netus", weight: 3},
{text: "et malesuada", weight: 3},
{text: "fames", weight: 2},
{text: "ac turpis", weight: 2},
{text: "egestas", weight: 2},
{text: "Aenean", weight: 2},
{text: "vestibulum", weight: 2},
{text: "elit", weight: 2},
{text: "sit amet", weight: 2},
{text: "metus", weight: 2},
{text: "adipiscing", weight: 2},
{text: "ut ultrices", weight: 2},
{text: "justo", weight: 1},
{text: "dictum", weight: 1},
{text: "Ut et leo", weight: 1},
{text: "metus", weight: 1},
{text: "at molestie", weight: 1},
{text: "purus", weight: 1},
{text: "Curabitur", weight: 1},
{text: "diam", weight: 1},
{text: "dui", weight: 1},
{text: "ullamcorper", weight: 1},
{text: "id vuluptate ut", weight: 1},
{text: "mattis", weight: 1},
{text: "et nulla", weight: 1},
{text: "Sed", weight: 1}].to_json.html_safe
%>
$(function() {
    console.log("word_list")
  $("#my_favorite_latin_words").jQCloud(word_list, {shape: "rectangular"});
});

</script>
<h1>jQCloud Example</h1>
<div id="my_favorite_latin_words" style="width: 550px; height: 350px; border: 1px solid #ccc;"></div>

app/views/default_scope/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-contro' %>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/default_scope/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user%>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <h1>
        <%= tmp_method("sdrgsdfgsdfgsdfgb http://www.bbc.com") %>
      </h1>
    </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Cloud", cloud_path %></li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", '#' %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p style="font-family: Sans-serif">
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
<div style="margin-top: 20px" class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/', class: "center kitten" %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user%>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>